// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgqI9TUq5ajZtZnO2KTAlqhV68hC2y5GY',
    appId: '1:822254013524:web:667281025770ec36a4f1c1',
    messagingSenderId: '822254013524',
    projectId: 'ibisa-5f758',
    authDomain: 'ibisa-5f758.firebaseapp.com',
    storageBucket: 'ibisa-5f758.appspot.com',
    measurementId: 'G-VZYLY5QN1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALtKLBlYFSx738pbxhAZI9UbGz5q-DU74',
    appId: '1:822254013524:android:60276e56a6cf399da4f1c1',
    messagingSenderId: '822254013524',
    projectId: 'ibisa-5f758',
    storageBucket: 'ibisa-5f758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBakyfINIt83T-cDNLyTUR9jymI7BFQ-kQ',
    appId: '1:822254013524:ios:ee5b5ab66c6f64ada4f1c1',
    messagingSenderId: '822254013524',
    projectId: 'ibisa-5f758',
    storageBucket: 'ibisa-5f758.appspot.com',
    androidClientId: '822254013524-ie23p0iv1gu6evkmiguttoq6kn5jg1td.apps.googleusercontent.com',
    iosClientId: '822254013524-1kd95k291dehsev8l1tp9i734qq8jr8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibisa',
  );
}
